config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end
  resources :charges, only: [:new, :create]
  resources :downgrade

  devise_for :users, controllers: { confirmations: 'confirmations' }

  get 'welcome/about'

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  root 'welcome#index'

  get 'welcome/index'

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  default_scope { order('created_at DESC') }

  before_save { self.private ||= false }

  scope :visible_to, -> (user) do
    return all if user.premium? || user.admin?
    where(private: [false, nill])
  end

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :user, presence: true

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if user_signed_in?
      if current_user.standard?
        @wikis = Wiki.where(private: false)
      else
        @wikis = policy_scope(Wiki)
      end
    else
      @wikis = policy_scope(Wiki)
    end
    @user = User.find_by(id: session[:user_id])
  end

  def show
    @wiki = Wiki.find(params[:id])
    @users = User.find_by(id: session[:user_id])
    @collaborators = @wiki.collaborators
  end

  def new
     @wiki = Wiki.new
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving your wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit(:body, :title, :private)
  end

end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<%= form_for [wiki] do |f| %>
  <% if wiki.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
      <ul>
        <% wiki.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(wiki.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  <% end %>
  <%= form_group_tag(wiki.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  <% end %>

  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% elsif current_user.standard? %>
    <%= f.hidden_field :private, :value => "false" %>
  <% end %>

  <div class="form-group">
    <%= f.submit "Save Wiki", class: 'btn btn-success' %>
  </div>

<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Public Wiki</h1>
  <div class="row">
    <div class="col-md-4">
      <p>Rules to follow when creating a Wiki.</p>
      <ul>
        <li>Do not create a wiki that already exists. </li>
        <li>Do not create a wiki that interferes with the Terms of Service.</li>
        <li>Any troll or useless wikis will be removed.</li>
      </ul>
    </div>
    <div class="col-md-8">
      <% if current_user %>
        <%= render 'form', wiki: @wiki %>
      <% end %>
    </div>
    <div class="form-group">
      <div class="col-md-4">
        <%= render partial: 'collaborators/form', locals: { wiki: @wiki } %>
      </div>
    </div>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
 <div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <% if user_signed_in? %>
            <% if current_user.premium? || current_user.admin? %>
              <h4 class="media-heading">
                <%= link_to wiki.title, wiki %>
              </h4>
            <% elsif wiki.private == false %>
              <h4 class="media-heading">
                <%= link_to wiki.title, wiki %>
              </h4>
            <% end %>
          <% else %>
            <% if wiki.private == false %>
              <h4 class="media-heading">
                <%= link_to wiki.title, wiki %>
              </h4>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <div class="col-md-4">
      <%= link_to "New Public Wiki", new_wiki_path, class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/wikis/new.html.erb
<h1>New Public Wiki</h1>
 <div class="row">
  <div class="col-md-4">
    <p>Rules to follow when creating a Wiki.</p>
    <ul>
      <li>Do not create a wiki that already exists. </li>
      <li>Do not create a wiki that interferes with the Terms of Service.</li>
      <li>Any troll or useless wikis will be removed.</li>
    </ul>
  </div>
  <% if current_user %>
  <div class="col-md-8">
    <%= render 'form', wiki: @wiki %>
  </div>
  <% end %>
</div>

app/views/wikis/show.html.erb
<div>
  <h2>
  <strong>
    <h1><%= markdown(@wiki.title) %></h1></p>
  </strong>
  </h2>
  <small>
    submitted <%= time_ago_in_words(@wiki.created_at) %> ago
  </small>
  <p> Private? <%= @wiki.private %></p>
  <%= render partial: 'collaborators/list' %>
</div>
 <div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
     <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
     <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
   </div>
 </div>