config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end
  resources :charges, only: [:new, :create]
  resources :downgrade

  devise_for :users, controllers: { confirmations: 'confirmations' }

  get 'welcome/about'

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  root 'welcome#index'

  get 'welcome/index'

end

app/controllers/downgrade_controller.rb
class DowngradeController < ApplicationController

  def new
  end

  def create
    current_user.update_attribute(:role, 'standard')
    current_user.wikis.each do |publicc|
      publicc.update_attribute(:private, false)
    end
    # re = Stripe::Refund.create( charge: "")
    flash[:notice] = "Your account has been downgraded to a standard account. Your private wikis are now public."
    redirect_to root_path
  end
end

app/helpers/downgrade_helper.rb
module DowngradeHelper
end

app/views/downgrade/create.html.erb
<h1>Downgrade#create</h1>
<p>Find me in app/views/downgrade/create.html.erb</p>

app/views/downgrade/new.html.erb
<%= form_tag charges_path do %>
<br>
<p>Your current membership level is: <strong><%= current_user.role %></strong></p>
  <% if current_user.role == 'premium' %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Refund your $15.00 and return to standard.</span>
      </label>
    </article>
  <%= link_to "Downgrade Account", downgrade_index_path, method: :create, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to downgrade your account? All of your private wikis will be made public, and you will have to pay again to upgrade your account later.' } %>
  <% end %>
<% end %>