config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end
  resources :charges, only: [:new, :create]
  resources :downgrade

  devise_for :users, controllers: { confirmations: 'confirmations' }

  get 'welcome/about'

  authenticated :user do
    root 'wikis#index', as: :authenticated_root
  end

  root 'welcome#index'

  get 'welcome/index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav nav-tabs">
        <%= link_to "Home", welcome_index_path, class: 'btn btn-primary' %>
        <%= link_to "About", welcome_about_path, class: 'btn btn-primary' %>
        <%= link_to "Wikis", wikis_path, class: 'btn btn-primary' %>
        <% if user_signed_in? %>
          <% if current_user.standard? %>
            <%= link_to 'Upgrade to Premium', new_charge_path, :class => 'btn btn-primary' %>
          <% elsif current_user.premium? %>
            <%= link_to 'Downgrade Your Account', new_downgrade_path, :class => 'btn btn-primary' %>
          <% end %>
        <% end %>
    </div>
    <% if user_signed_in? %>
      Signed in as: <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit Account', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>